# version: 1

# Add 'Ongoing translation' label to any change within the 'strings.xml' files

Ongoing translation:

- src/**/*.strings.xml

- app/src/main/res/values-uk/*

- app/src/main/res/values-tr/*

- app/src/main/res/values-pt-rPT/*

- app/src/main/res/values-iw/*

- app/src/main/res/values-fr-rFR/*

- app/src/main/res/values-es/*

# Add 'gradle' label to any change to *.gradle files within the source dir

gradle:

- gradle/.*

- gradle.properties

- gradlew

# Add 'wiki' label to any change to files within the source dir

wiki:

- wiki/.*
