# version: 1

# Add 'Ongoing translation' label to any change to *.strings.xml and *default.txt files within the source dir
Ongoing translation:
- app/src/main/**/*.strings.xml
- app/src/main/**/*.default.txt
- app/src/main/res/values-fr-rFR/strings.xml

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['values-fr-rFR/*.xml']
  all: ['!values/strings.xml']
