# version: 1

# Add 'Ongoing translation' label to any change to *.strings.xml and *default.txt files within the source dir
Ongoing translation:
- app/src/main/**/*.strings.xml
- app/src/main/**/*.default.txt
