name: Question
description: Ask a question, related to the functioning or use of URLCheck
labels: [question]
body:

  - type: dropdown
    id: question_type
    attributes:
      label: Is your question related to...
      options:
        - how something works?
        - how to use something?
        - other?
    validations:
      required: true
      
  - type: textarea
    id: question
    attributes:
      label: Please state your question related to URLCheck.
      description: Question around URLCheck
      placeholder: |
        Examples:
          "How does the URL Cleaner updater works?"
          "How can I use the pattern checker module?"
          "I have a question about your privacy policy..."
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Others things
      placeholder: |
       "[...]"

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      placeholder: |
       If needed, provide one or more screenshot(s)

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true

